# Generated by Django 3.0.1 on 2019-12-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollectorServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTScans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(unique=True)),
                ('address', models.CharField(max_length=17)),
                ('bound', models.BooleanField()),
            ],
        ),
    ]
