# Generated by Django 3.0.1 on 2019-12-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollectorServer', '0002_btscans'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(unique=True)),
                ('battery_percentage', models.FloatField()),
                ('is_charging', models.BooleanField()),
            ],
        ),
    ]
